import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  en: {
    nav: {
      tagline: "Smart Hiring Platform",
      login: "Log in",
      getStarted: "Get started",
      backHome: "Back home",
    },
    footer: { rights: "© 2026 Mamoun. All rights reserved." },
    home: {
      badge: "AI · Smart Matching · Multilingual · Global Hiring",
      titleLine1: "Smarter hiring,",
      titleLine2: "simpler than ever.",
      subtitle: "From CV upload to the hiring decision — all in one platform.",
      findJob: "Find a job",
      findEmployee: "Find an employee",
      trust: "A smart hiring platform supporting teams around the world.",
      aboutBadge: "About us",
      aboutTitle: "Mamoun — your smart hiring partner",
      aboutDesc:
        "Mamoun is a global hiring platform combining AI with personality assessment to match the right candidate to the right role — with full transparency, and multilingual support for teams worldwide.",
      statGlobal: "Global",
      statGlobalLabel: "Worldwide coverage",
      statJobs: "1,200+",
      statJobsLabel: "Jobs posted",
      statMatch: "85%",
      statMatchLabel: "Match accuracy",
      statHire: "48h",
      statHireLabel: "Avg. hire time",
      featureMatchTitle: "AI-powered matching",
      featureMatchDesc: "Skills · Experience · Personality",
      featureCvTitle: "Instant CV parsing",
      featureCvDesc: "PDF → structured profile in seconds",
      featurePipelineTitle: "Pipeline analytics",
      featurePipelineDesc: "Track every stage in real time",
      featurePersonalityTitle: "Personality assessment",
      featurePersonalityDesc: "6 questions that reveal culture fit",
      jobsTitle: "Latest Job Postings",
      viewAll: "View all",
      ctaTitle: "Ready to get started?",
      ctaSubtitle: "Sign up now and launch your journey in minutes.",
      findRole: "Find a role",
      hireTalent: "Hire talent",
    },
    getStarted: {
      title: "How will you use Mamoun?",
      subtitle: "You can switch later. This just tailors your onboarding.",
      candidateBadge: "Candidate",
      candidateTitle: "I'm looking for a role",
      candidatePoints: ["CV parsed in seconds", "Personality-aware matching", "One place for every application"],
      continueCandidate: "Continue as candidate",
      employerBadge: "Employer",
      employerTitle: "I'm hiring talent",
      employerPoints: ["Explainable AI matching", "Kanban pipeline", "Team & permissions"],
      continueEmployer: "Continue as employer",
      haveAccount: "Already have an account?",
      logIn: "Log in",
    },
    auth: {
      loginTitle: "Welcome back",
      loginSubtitle: "Log in to continue.",
      email: "Email",
      workEmail: "Work email",
      password: "Password",
      forgotPassword: "Forgot password?",
      loginBtn: "Log in",
      or: "OR",
      continueDemo: "Continue with demo account",
      newHere: "New here?",
      noAccount: "Don't have an account?",
      getStartedLink: "Get started",
      signupTitle: "Create your account",
      signupSubtitleCandidate: "Set up your profile and start applying.",
      signupSubtitleEmployer: "Set up your company profile and start hiring.",
      fullName: "Full name",
      createAccount: "Create account",
      alreadyHaveAccount: "Already have an account?",
      continuingAs: "YOU'LL CONTINUE AS",
      changeRole: "Change",
      oneAccountTwoExperiences: "One account. Two experiences.",
      namePlaceholder: "Jane Doe",
      emailPlaceholder: "you@company.com",
      builtWithIntelligence: "Built with intelligence",
      testimonialQuote: "We cut time-to-hire from 41 days to 19. The pipeline finally matches how we actually decide.",
      help: "Help",

      // Forgot / Reset password
      forgotTitle: "Forgot your password?",
      forgotSubtitle: "Enter your email and we'll send you a reset link.",
      sendResetLink: "Send reset link",
      sending: "Sending...",
      backToLogin: "Back to login",
      checkEmailTitle: "Check your email",
      checkEmailSubtitle: "We sent a password reset link to",
      resetTitle: "Set a new password",
      resetSubtitle: "Choose a strong password you haven't used before.",
      newPassword: "New password",
      confirmPassword: "Confirm password",
      resetPasswordBtn: "Reset password",
      resetSuccessTitle: "Password updated",
      resetSuccessSubtitle: "Your password has been changed successfully. You can log in now.",
      invalidLinkTitle: "Invalid or expired link",
      invalidLinkSubtitle: "This password reset link is no longer valid. Please request a new one.",
      passwordTooShort: "Password must be at least 8 characters.",
      passwordsDontMatch: "Passwords don't match.",
      resetFailed: "Something went wrong. Please try again.",
    },
    onboarding: {
      stepLabel: "Step",
      stepOf: "of 3",
      steps: ["Basic profile", "CV & skills", "Personality"],
      basicsTitle: "Tell us the basics",
      basicsSubtitle: "You can edit anything later.",
      fullName: "Full name",
      email: "Email",
      phone: "Phone",
      city: "City",
      yearsExp: "Years of experience",
      jobTitle: "Current or desired job title",
      saveDraft: "Save draft",
      continueBtn: "Continue",
      cvTitle: "Upload your CV",
      cvSubtitle: "We'll extract your skills, roles, and education so you don't retype them.",
      dropzoneText: "Drag & drop your CV, or",
      browseFiles: "browse files",
      fileHint: "PDF or DOCX · max 10MB",
      back: "Back",
      skip: "Skip for now",
      personalityTitle: "A short, respectful assessment",
      personalitySubtitle: "Six statements. No wrong answers — signal, not judgement.",
      assessmentLabel: "Mamoun · assessment",
      questionOf: "Question",
      of: "of",
      previous: "Previous",
      thankYouTitle: "Thank you!",
      thankYouSubtitle:
        "Your answers have been recorded. Your profile is now complete and ready to be matched with the best roles.",
      goToDashboard: "Go to dashboard",
      scale: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
      questions: [
        "I stay calm when priorities shift suddenly.",
        "I enjoy working closely with other people on shared goals.",
        "I keep going even when a task turns out to be harder than expected.",
        "I like having a clear plan before I start something new.",
        "I speak up when I notice a better way to do something.",
        "I recover quickly after receiving critical feedback.",
      ],
      experienceOptions: ["0-1", "1-3", "3-5", "5-8", "8+"],
    },
    candidate: {
      navDashboard: "Dashboard",
      navJobs: "Jobs",
      navApplications: "Applications",
      navMessages: "Messages",
      navProfile: "Profile",
      roleLabel: "Candidate",
      boostTitle: "Boost your chances",
      boostSubtitle: "Complete your profile to rank higher with employers.",
      boostCta: "Complete profile",
      logout: "Log out",
      langToggle: "العربية",
      searchPlaceholder: "Search...",
      welcome: "Welcome,",
      welcomeSubtitle: "Your profile is live. Here are roles matched to you today.",
      activeApplications: "Active applications",
      recommendedForYou: "Recommended for you",
      aiRanked: "AI ranked",
      viewJob: "View job",
      jobsTitle: "Jobs",
      jobsSubtitle: "Browse every open role.",
      searchJobs: "Search title, company, skill...",
      allWorkModels: "All work models",
      noMatch: "No roles match your search.",
      backToDashboard: "Back to dashboard",
      aboutRole: "About the role",
      requirements: "Requirements",
      salary: "Salary",
      apply: "Apply",
      applied: "Applied",
      match: "Match",
      skills: "Skills",
      experience: "Experience",
      personality: "Personality",
      applyModalTitle: "Apply to this role",
      coverNote: "Cover note (optional)",
      coverNotePlaceholder: "I'm excited about this role because...",
      coverNoteHint: "Tell them why you're a great fit.",
      cancel: "Cancel",
      submit: "Submit application",
      myApplications: "My applications",
      noApplications: "You haven't applied to any jobs yet.",
      browseRoles: "Browse open roles",
      messagesTitle: "Messages",
      messagesSubtitle: "Conversations with employers will show up here.",
      noMessages: "No messages yet.",
      myProfile: "My profile",
      profileSubtitle: "Update your info any time. It powers AI matching.",
      basics: "Basics",
      jobTitle: "Job title",
      retake: "Retake",
      saveChanges: "Save changes",
      addSkill: "Add skill",
      completeAssessment: "Complete the assessment to see your results here.",
      fromCv: "from CV",
      personalityAssessment: "Personality assessment",
      resilience: "Resilience",
      collaboration: "Collaboration",
      focus: "Focus",
      initiative: "Initiative",
    },
    employer: {
      navDashboard: "Dashboard",
      navJobs: "Jobs",
      navCandidates: "Candidates",
      navAnalytics: "Analytics",
      roleLabel: "Employer",
      logout: "Log out",
      welcome: "Welcome,",
      welcomeSubtitle: "Here's what needs your attention today.",
      createJob: "Create job",
      pipelineSnapshot: "Pipeline snapshot",
      noJobsYet: "No jobs yet.",
      createFirstJob: "Create your first job",
      inPipeline: "in pipeline",
      jobsTitle: "Jobs",
      jobsSubtitle: "Every role you've posted.",
      aiMatched: "AI · matched",
      allJobs: "All jobs",
      pipeline: "Pipeline",
      aiMatchedCandidates: "AI-matched candidates",
      noCandidatesYet: "No candidates yet.",
      view: "View",
      moveForward: "Move forward",
      reject: "Reject",
      stageNew: "New",
      stageScreening: "Screening",
      stageInterview: "Interview",
      stageOffer: "Offer",
      stageHired: "Hired",
      stageRejected: "Rejected",
      whyRanking: "Why this ranking?",
      overallMatch: "Overall match",
      skills: "Skills",
      experience: "Experience",
      personality: "Personality",
      createJobTitle: "Create a job",
      stepBasics: "Basics",
      stepSkills: "Skills & requirements",
      stepPersonality: "Personality fit",
      stepPublish: "Publish",
      jobTitleLabel: "Job title",
      cityLabel: "City",
      workModel: "Work model",
      workModels: ["Onsite", "Hybrid", "Remote"],
      salaryRange: "Salary range",
      description: "Description",
      next: "Next",
      back: "Back",
      requiredSkills: "Required skills (comma separated)",
      requirementsLabel: "Requirements (one per line)",
      personalityQuestion: "What personality traits fit this role?",
      personalitySubtitle:
        "Set the ideal target for each trait. Candidates are matched to how close they land — no wrong answers.",
      lowerPriority: "Lower priority",
      essential: "Essential",
      calloutText: "Candidates take the assessment during onboarding. Their scores are compared against your targets.",
      livePreview: "Live AI preview",
      analyzed: "Analyzed",
      candidatesWord: "candidates",
      jobPreview: "Job preview",
      personalityTarget: "Personality target",
      publishJob: "Publish job",
      candidatesTitle: "Candidates",
      candidatesSubtitle: "Every candidate across every role — AI ranked.",
      noCandidatesGlobal: "No candidates yet — publish a job to get AI matches.",
      allStages: "All stages",
      candidateCol: "Candidate",
      roleCol: "Job",
      stageCol: "Stage",
      matchCol: "Match",
      analyticsTitle: "Analytics",
      analyticsSubtitle: "A quick snapshot across your hiring activity.",
      openJobs: "Open jobs",
      candidatesInPipeline: "Candidates in pipeline",
      offersMade: "Offers made",
      yrs: "yrs",
      skillsMatch: "skills match",
      yrsExperience: "yrs experience",
      basedIn: "Based in",
      applyingTo: "applying to",
      profileTitle: "Company profile",
      profileSubtitle: "This information appears on every job you post.",
      contactName: "Contact name",
      companyName: "Company name",
      industry: "Industry",
      teamSize: "Team size",
      website: "Website",
      saveChanges: "Save changes",
      savedMessage: "Saved.",
    },
  },

  ar: {
    nav: {
      tagline: "منصة توظيف ذكية",
      login: "تسجيل الدخول",
      getStarted: "ابدأ الآن",
      backHome: "الصفحة الرئيسية",
    },
    footer: { rights: "© 2026 مأمون. جميع الحقوق محفوظة." },
    home: {
      badge: "ذكاء اصطناعي · مطابقة ذكية · متعدد اللغات · توظيف عالمي",
      titleLine1: "توظيف أكثر ذكاءً،",
      titleLine2: "أسهل من أي وقت مضى.",
      subtitle: "من رفع السيرة الذاتية إلى قرار التوظيف — كل ذلك في منصة واحدة.",
      findJob: "ابحث عن وظيفة",
      findEmployee: "ابحث عن موظف",
      trust: "منصة توظيف ذكية تدعم فرق العمل حول العالم.",
      aboutBadge: "من نحن",
      aboutTitle: "مأمون — شريكك في التوظيف الذكي",
      aboutDesc:
        "مأمون منصة توظيف عالمية تجمع بين الذكاء الاصطناعي وتقييم الشخصية لمطابقة المرشح المناسب مع الدور المناسب — بشفافية كاملة، ودعم متعدد اللغات لفرق العمل حول العالم.",
      statGlobal: "عالمي",
      statGlobalLabel: "تغطية عالمية",
      statJobs: "+1,200",
      statJobsLabel: "وظيفة منشورة",
      statMatch: "85%",
      statMatchLabel: "دقة المطابقة",
      statHire: "48 ساعة",
      statHireLabel: "متوسط وقت التوظيف",
      featureMatchTitle: "مطابقة بالذكاء الاصطناعي",
      featureMatchDesc: "المهارات · الخبرة · الشخصية",
      featureCvTitle: "تحليل فوري للسيرة الذاتية",
      featureCvDesc: "من ملف PDF إلى ملف منظم في ثوانٍ",
      featurePipelineTitle: "تحليلات المسار الوظيفي",
      featurePipelineDesc: "تابع كل مرحلة لحظة بلحظة",
      featurePersonalityTitle: "تقييم الشخصية",
      featurePersonalityDesc: "ستة أسئلة توضح مدى التوافق مع ثقافة الشركة",
      jobsTitle: "أحدث الوظائف الشاغرة",
      viewAll: "عرض الكل",
      ctaTitle: "هل أنت مستعد للبدء؟",
      ctaSubtitle: "سجّل الآن وابدأ رحلتك في دقائق.",
      findRole: "ابحث عن وظيفة",
      hireTalent: "وظّف الكفاءات",
    },
    getStarted: {
      title: "كيف تريد استخدام مأمون؟",
      subtitle: "يمكنك التغيير لاحقًا. هذا فقط يُخصص تجربة التسجيل الخاصة بك.",
      candidateBadge: "باحث عن عمل",
      candidateTitle: "أبحث عن وظيفة",
      candidatePoints: ["تحليل السيرة الذاتية في ثوانٍ", "مطابقة مبنية على الشخصية", "مكان واحد لجميع طلباتك"],
      continueCandidate: "المتابعة كباحث عن عمل",
      employerBadge: "صاحب عمل",
      employerTitle: "أبحث عن كفاءات للتوظيف",
      employerPoints: ["مطابقة ذكاء اصطناعي واضحة المعايير", "لوحة متابعة المرشحين", "فريق وصلاحيات"],
      continueEmployer: "المتابعة كصاحب عمل",
      haveAccount: "لديك حساب بالفعل؟",
      logIn: "تسجيل الدخول",
    },
    auth: {
      loginTitle: "مرحبًا بعودتك",
      loginSubtitle: "سجّل دخولك لمتابعة الاستخدام.",
      email: "البريد الإلكتروني",
      workEmail: "البريد الإلكتروني الوظيفي",
      password: "كلمة المرور",
      forgotPassword: "هل نسيت كلمة المرور؟",
      loginBtn: "تسجيل الدخول",
      or: "أو",
      continueDemo: "المتابعة بحساب تجريبي",
      newHere: "مستخدم جديد؟",
      noAccount: "ليس لديك حساب؟",
      getStartedLink: "ابدأ الآن",
      signupTitle: "أنشئ حسابك",
      signupSubtitleCandidate: "أعدّ ملفك الشخصي وابدأ التقديم على الوظائف.",
      signupSubtitleEmployer: "أعدّ ملف شركتك وابدأ عملية التوظيف.",
      fullName: "الاسم الكامل",
      createAccount: "إنشاء حساب",
      alreadyHaveAccount: "لديك حساب بالفعل؟",
      continuingAs: "ستتابع كـ",
      changeRole: "تغيير",
      oneAccountTwoExperiences: "حساب واحد. تجربتان مختلفتان.",
      namePlaceholder: "محمد أحمد",
      emailPlaceholder: "you@company.com",
      builtWithIntelligence: "مبني بالذكاء الاصطناعي",
      testimonialQuote: "خفّضنا وقت التوظيف من 41 يومًا إلى 19 يومًا فقط. أصبح المسار الوظيفي يعكس فعليًا طريقة اتخاذنا للقرار.",
      help: "مساعدة",

      // نسيت كلمة المرور / إعادة التعيين
      forgotTitle: "هل نسيت كلمة المرور؟",
      forgotSubtitle: "أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين.",
      sendResetLink: "إرسال رابط إعادة التعيين",
      sending: "جارٍ الإرسال...",
      backToLogin: "العودة إلى تسجيل الدخول",
      checkEmailTitle: "تحقق من بريدك الإلكتروني",
      checkEmailSubtitle: "أرسلنا رابط إعادة تعيين كلمة المرور إلى",
      resetTitle: "تعيين كلمة مرور جديدة",
      resetSubtitle: "اختر كلمة مرور قوية لم تستخدمها من قبل.",
      newPassword: "كلمة المرور الجديدة",
      confirmPassword: "تأكيد كلمة المرور",
      resetPasswordBtn: "إعادة تعيين كلمة المرور",
      resetSuccessTitle: "تم تحديث كلمة المرور",
      resetSuccessSubtitle: "تم تغيير كلمة مرورك بنجاح. يمكنك تسجيل الدخول الآن.",
      invalidLinkTitle: "رابط غير صالح أو منتهي الصلاحية",
      invalidLinkSubtitle: "رابط إعادة تعيين كلمة المرور هذا لم يعد صالحًا. يرجى طلب رابط جديد.",
      passwordTooShort: "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.",
      passwordsDontMatch: "كلمتا المرور غير متطابقتين.",
      resetFailed: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    },
    onboarding: {
      stepLabel: "خطوة",
      stepOf: "من 3",
      steps: ["الملف الأساسي", "السيرة الذاتية والمهارات", "الشخصية"],
      basicsTitle: "أخبرنا ببياناتك الأساسية",
      basicsSubtitle: "يمكنك تعديل أي شيء لاحقًا.",
      fullName: "الاسم الكامل",
      email: "البريد الإلكتروني",
      phone: "رقم الهاتف",
      city: "المدينة",
      yearsExp: "سنوات الخبرة",
      jobTitle: "المسمى الوظيفي الحالي أو المطلوب",
      saveDraft: "حفظ كمسودة",
      continueBtn: "متابعة",
      cvTitle: "ارفع سيرتك الذاتية",
      cvSubtitle: "سنستخرج مهاراتك وخبراتك ومؤهلاتك التعليمية حتى لا تُعيد كتابتها.",
      dropzoneText: "اسحب وأفلت سيرتك الذاتية، أو",
      browseFiles: "تصفّح الملفات",
      fileHint: "PDF أو DOCX · بحد أقصى 10 ميجابايت",
      back: "رجوع",
      skip: "تخطّي الآن",
      personalityTitle: "تقييم قصير ومحترم",
      personalitySubtitle: "ست عبارات. لا توجد إجابة خاطئة — الهدف هو استخلاص مؤشر، لا إصدار حكم.",
      assessmentLabel: "مأمون · التقييم",
      questionOf: "سؤال",
      of: "من",
      previous: "السابق",
      thankYouTitle: "شكرًا لك!",
      thankYouSubtitle:
        "تم تسجيل إجاباتك. أصبح ملفك الشخصي مكتملًا وجاهزًا للمطابقة مع أفضل الوظائف.",
      goToDashboard: "الانتقال إلى لوحة التحكم",
      scale: ["غير موافق بشدة", "غير موافق", "محايد", "موافق", "موافق بشدة"],
      questions: [
        "أبقى هادئًا عندما تتغير الأولويات فجأة.",
        "أستمتع بالعمل عن قرب مع الآخرين لتحقيق هدف مشترك.",
        "أواصل العمل حتى عندما تكون المهمة أصعب مما توقعت.",
        "أفضّل أن تكون لديّ خطة واضحة قبل البدء بأي أمر جديد.",
        "أُعبّر عن رأيي عندما ألاحظ طريقة أفضل لأداء عمل ما.",
        "أستعيد توازني بسرعة بعد تلقّي ملاحظات نقدية.",
      ],
      experienceOptions: ["0-1", "1-3", "3-5", "5-8", "8+"],
    },
    candidate: {
      navDashboard: "الرئيسية",
      navJobs: "الوظائف",
      navApplications: "طلباتي",
      navMessages: "الرسائل",
      navProfile: "الملف الشخصي",
      roleLabel: "باحث عن عمل",
      boostTitle: "عزّز فرصتك",
      boostSubtitle: "أكمل ملفك الشخصي عشان تظهر بترتيب أعلى لأصحاب العمل.",
      boostCta: "أكمل ملفك الشخصي",
      logout: "تسجيل الخروج",
      langToggle: "English",
      searchPlaceholder: "بحث...",
      welcome: "مرحبًا بك،",
      welcomeSubtitle: "ملفك الشخصي نشط. إليك الوظائف المطابقة لك اليوم.",
      activeApplications: "الطلبات النشطة",
      recommendedForYou: "موصى بها لك",
      aiRanked: "مرتبة بالذكاء الاصطناعي",
      viewJob: "عرض الوظيفة",
      jobsTitle: "الوظائف",
      jobsSubtitle: "تصفّح جميع الوظائف المتاحة.",
      searchJobs: "ابحث بالمسمى أو الشركة أو المهارة...",
      allWorkModels: "جميع أنظمة العمل",
      noMatch: "لا توجد وظائف مطابقة لبحثك.",
      backToDashboard: "العودة إلى الرئيسية",
      aboutRole: "عن الوظيفة",
      requirements: "المتطلبات",
      salary: "الراتب",
      apply: "تقديم",
      applied: "تم التقديم",
      match: "نسبة التطابق",
      skills: "المهارات",
      experience: "الخبرة",
      personality: "الشخصية",
      applyModalTitle: "التقديم على هذه الوظيفة",
      coverNote: "رسالة تعريفية (اختياري)",
      coverNotePlaceholder: "أنا متحمس لهذه الوظيفة لأن...",
      coverNoteHint: "أخبرهم لماذا أنت الشخص المناسب.",
      cancel: "إلغاء",
      submit: "إرسال الطلب",
      myApplications: "طلباتي",
      noApplications: "لم تتقدم لأي وظيفة بعد.",
      browseRoles: "تصفّح الوظائف المتاحة",
      messagesTitle: "الرسائل",
      messagesSubtitle: "ستظهر هنا محادثاتك مع أصحاب العمل.",
      noMessages: "لا توجد رسائل بعد.",
      myProfile: "ملفي الشخصي",
      profileSubtitle: "حدّث بياناتك في أي وقت. هذا يعزز دقة المطابقة بالذكاء الاصطناعي.",
      basics: "البيانات الأساسية",
      jobTitle: "المسمى الوظيفي",
      retake: "إعادة التقييم",
      saveChanges: "حفظ التغييرات",
      addSkill: "إضافة مهارة",
      completeAssessment: "أكمل التقييم لعرض نتائجك هنا.",
      fromCv: "من السيرة الذاتية",
      personalityAssessment: "تقييم الشخصية",
      resilience: "الصلابة النفسية",
      collaboration: "التعاون",
      focus: "التركيز",
      initiative: "روح المبادرة",
    },
    employer: {
      navDashboard: "الرئيسية",
      navJobs: "الوظائف",
      navCandidates: "المرشحون",
      navAnalytics: "التحليلات",
      roleLabel: "صاحب عمل",
      logout: "تسجيل الخروج",
      welcome: "مرحبًا بك،",
      welcomeSubtitle: "إليك ما يحتاج إلى اهتمامك اليوم.",
      createJob: "إنشاء وظيفة",
      pipelineSnapshot: "لمحة عن المسار الوظيفي",
      noJobsYet: "لا توجد وظائف بعد.",
      createFirstJob: "أنشئ وظيفتك الأولى",
      inPipeline: "في المسار الوظيفي",
      jobsTitle: "الوظائف",
      jobsSubtitle: "جميع الوظائف التي قمت بنشرها.",
      aiMatched: "ذكاء اصطناعي · مطابقة",
      allJobs: "جميع الوظائف",
      pipeline: "المسار الوظيفي",
      aiMatchedCandidates: "مرشحون مطابقون بالذكاء الاصطناعي",
      noCandidatesYet: "لا يوجد مرشحون بعد.",
      view: "عرض",
      moveForward: "الانتقال إلى المرحلة التالية",
      reject: "رفض",
      stageNew: "جديد",
      stageScreening: "الفرز الأولي",
      stageInterview: "مقابلة",
      stageOffer: "عرض عمل",
      stageHired: "تم التعيين",
      stageRejected: "مرفوض",
      whyRanking: "لماذا هذا الترتيب؟",
      overallMatch: "نسبة التطابق الإجمالية",
      skills: "المهارات",
      experience: "الخبرة",
      personality: "الشخصية",
      createJobTitle: "إنشاء وظيفة",
      stepBasics: "البيانات الأساسية",
      stepSkills: "المهارات والمتطلبات",
      stepPersonality: "توافق الشخصية",
      stepPublish: "النشر",
      jobTitleLabel: "المسمى الوظيفي",
      cityLabel: "المدينة",
      workModel: "نظام العمل",
      workModels: ["حضوري", "هجين", "عن بُعد"],
      salaryRange: "نطاق الراتب",
      description: "الوصف",
      next: "التالي",
      back: "رجوع",
      requiredSkills: "المهارات المطلوبة (مفصولة بفواصل)",
      requirementsLabel: "المتطلبات (سطر لكل متطلب)",
      personalityQuestion: "ما السمات الشخصية المناسبة لهذا الدور؟",
      personalitySubtitle: "حدّد المستوى المثالي لكل سمة. تتم مطابقة المرشحين حسب مدى قربهم من الهدف — لا توجد إجابة خاطئة.",
      lowerPriority: "أولوية أقل",
      essential: "أساسي",
      calloutText: "يخضع المرشحون لهذا التقييم أثناء التسجيل. تُقارن نتائجهم بالأهداف التي حددتها.",
      livePreview: "معاينة حية بالذكاء الاصطناعي",
      analyzed: "تم تحليل",
      candidatesWord: "مرشح",
      jobPreview: "معاينة الوظيفة",
      personalityTarget: "الهدف من حيث الشخصية",
      publishJob: "نشر الوظيفة",
      candidatesTitle: "المرشحون",
      candidatesSubtitle: "كل مرشح في كل وظيفة — مرتبون بالذكاء الاصطناعي.",
      noCandidatesGlobal: "لا يوجد مرشحون بعد — انشر وظيفة للحصول على ترشيحات بالذكاء الاصطناعي.",
      allStages: "جميع المراحل",
      candidateCol: "المرشح",
      roleCol: "الوظيفة",
      stageCol: "المرحلة",
      matchCol: "التطابق",
      analyticsTitle: "التحليلات",
      analyticsSubtitle: "لمحة سريعة عن نشاط التوظيف الخاص بك.",
      openJobs: "وظائف مفتوحة",
      candidatesInPipeline: "مرشحون في المسار الوظيفي",
      offersMade: "عروض عمل مُرسلة",
      yrs: "سنة خبرة",
      skillsMatch: "تطابق المهارات",
      yrsExperience: "سنة خبرة",
      basedIn: "مقيم في",
      applyingTo: "يتقدم على",
      profileTitle: "الملف الشخصي للشركة",
      profileSubtitle: "تظهر هذه المعلومات في كل وظيفة تنشرها.",
      contactName: "اسم جهة الاتصال",
      companyName: "اسم الشركة",
      industry: "المجال",
      teamSize: "حجم الفريق",
      website: "الموقع الإلكتروني",
      saveChanges: "حفظ التغييرات",
      savedMessage: "تم الحفظ.",
    },
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("mamoun-lang") || "en");

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    try {
      localStorage.setItem("mamoun-lang", lang);
    } catch {
      /* ignore */
    }
  }, [lang]);

  const toggleLang = () => setLang((prev) => (prev === "en" ? "ar" : "en"));

  const t = useMemo(() => {
    const dict = translations[lang];
    return (path) => {
      const parts = path.split(".");
      let value = dict;
      for (const part of parts) {
        value = value?.[part];
      }
      return value ?? path;
    };
  }, [lang]);

  const value = useMemo(() => ({ lang, dir: lang === "ar" ? "rtl" : "ltr", toggleLang, t }), [lang, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within a LanguageProvider");
  return ctx;
}
